import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("workflow dashboard pages stay wired to the API flow", () => {
  assert.match(read("src/app/page.tsx"), /listWorkflowRuns/);
  assert.match(read("src/app/page.tsx"), /getHumanFeedbackSummary/);
  assert.match(read("src/app/page.tsx"), /Human Feedback Loop/);
  assert.match(read("src/app/workflow-runs/page.tsx"), /listWorkflowRuns/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /getWorkflowRun/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /getUploadedInput/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /listAgentSteps/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /listWorkflowEvents/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /listHumanApprovals/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /Observability Timeline/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /RecoverySummary/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /final-output/);
  assert.match(read("src/app/workflow-runs/[id]/final-output/page.tsx"), /Final Executive Summary/);
  assert.match(read("src/app/workflow-runs/[id]/final-output/page.tsx"), /Workflow Trace/);
  assert.match(read("src/app/workflow-runs/[id]/final-output/page.tsx"), /listAgentSteps/);
  assert.match(read("src/app/human-approvals/page.tsx"), /listHumanApprovals/);
  assert.match(read("src/app/human-approvals/[id]/page.tsx"), /getHumanApproval/);
  assert.match(read("src/app/human-approvals/[id]/actions.ts"), /approveHumanApproval/);
  assert.match(read("src/app/human-approvals/[id]/actions.ts"), /requestHumanApprovalRetry/);
  assert.match(read("src/app/human-approvals/[id]/actions.ts"), /rejectHumanApproval/);
  assert.match(read("src/app/human-approvals/[id]/actions.ts"), /editHumanApproval/);
  assert.match(read("src/app/human-approvals/[id]/page.tsx"), /StructuredAnalysisEditor/);
  assert.match(read("src/app/human-approvals/[id]/page.tsx"), /analysis_key_findings/);
  assert.match(read("src/app/human-approvals/[id]/page.tsx"), /analysis_top_insights/);
  assert.match(read("src/app/human-approvals/[id]/page.tsx"), /analysis_suspected_root_cause/);
  assert.match(read("src/app/human-approvals/[id]/actions.ts"), /getEditedAnalysis/);
  assert.match(read("src/app/costs/page.tsx"), /Cost Dashboard/);
  assert.match(read("src/app/costs/page.tsx"), /listWorkflowRuns/);
  assert.match(read("src/app/costs/page.tsx"), /listAgentSteps/);
  assert.match(read("src/components/nav.tsx"), /href="\/costs"/);
  assert.match(read("src/components/nav.tsx"), /href="\/evaluation"/);
  assert.match(read("src/components/nav.tsx"), /href="\/agent-performance"/);
  assert.match(read("src/components/nav.tsx"), /href="\/workflow-comparison"/);
  assert.match(read("src/components/nav.tsx"), /href="\/failures"/);
  assert.match(read("src/components/nav.tsx"), /href="\/improvements"/);
  assert.match(read("src/components/nav.tsx"), /href="\/prompt-versions"/);
  assert.match(read("src/components/nav.tsx"), /href="\/settings"/);
  assert.match(read("src/app/evaluation/page.tsx"), /Evaluation Dashboard/);
  assert.match(read("src/app/evaluation/page.tsx"), /getEvaluationSummary/);
  assert.match(read("src/app/evaluation/page.tsx"), /Router Accuracy/);
  assert.match(read("src/app/evaluation/page.tsx"), /Export CSV/);
  assert.match(read("src/app/evaluation/page.tsx"), /Export JSON/);
  assert.match(read("src/app/evaluation/page.tsx"), /Export Markdown/);
  assert.match(read("src/app/agent-performance/page.tsx"), /Agent Performance Dashboard/);
  assert.match(read("src/app/agent-performance/page.tsx"), /getAgentPerformanceSummary/);
  assert.match(read("src/app/agent-performance/page.tsx"), /Schema Validation Failures/);
  assert.match(read("src/app/workflow-comparison/page.tsx"), /Workflow Comparison/);
  assert.match(read("src/app/workflow-comparison/page.tsx"), /getEvaluationComparisons/);
  assert.match(read("src/app/workflow-comparison/page.tsx"), /Reviewer Issues/);
  assert.match(read("src/app/failures/page.tsx"), /Failure Case Explorer/);
  assert.match(read("src/app/failures/page.tsx"), /listWorkflowRuns/);
  assert.match(read("src/app/failures/page.tsx"), /Schema Validation Failures/);
  assert.match(read("src/app/improvements/page.tsx"), /Improvement Tracking/);
  assert.match(read("src/app/improvements/page.tsx"), /listEvaluationResults/);
  assert.match(read("src/app/improvements/page.tsx"), /Evaluation Trends/);
  assert.match(read("src/app/prompt-versions/page.tsx"), /Prompt Versions/);
  assert.match(read("src/app/prompt-versions/page.tsx"), /listPromptVersions/);
  assert.match(read("src/app/prompt-versions/form.tsx"), /useActionState/);
  assert.match(read("src/app/prompt-versions/[id]/page.tsx"), /Activate Prompt/);
  assert.match(read("src/app/settings/page.tsx"), /Agent Settings/);
  assert.match(read("src/app/settings/page.tsx"), /listAgentSettings/);
  assert.match(read("src/app/settings/settings-form.tsx"), /useActionState/);
  assert.match(read("src/app/settings/actions.ts"), /updateAgentSetting/);
  assert.match(read("src/app/workflow-runs/[id]/actions.ts"), /runSalesAnalyst/);
  assert.match(read("src/app/workflow-runs/[id]/actions.ts"), /runSalesBaseline/);
  assert.match(read("src/app/workflow-runs/[id]/actions.ts"), /runSalesReviewer/);
  assert.match(read("src/app/workflow-runs/[id]/actions.ts"), /runSalesWriter/);
  assert.match(read("src/app/workflow-runs/[id]/actions.ts"), /cancelWorkflowRun/);
  assert.match(read("src/app/workflow-runs/[id]/run-analyst-form.tsx"), /useActionState/);
  assert.match(read("src/app/workflow-runs/[id]/run-baseline-form.tsx"), /useActionState/);
  assert.match(read("src/app/workflow-runs/[id]/run-reviewer-form.tsx"), /useActionState/);
  assert.match(read("src/app/workflow-runs/[id]/run-writer-form.tsx"), /useActionState/);
  assert.match(read("src/app/workflow-runs/[id]/cancel-workflow-form.tsx"), /Cancel Workflow/);
  assert.match(read("src/app/workflow-runs/new/actions.ts"), /createWorkflowRun/);
  assert.match(read("src/app/workflow-runs/new/actions.ts"), /createUploadedInput/);
  assert.match(read("src/app/workflow-runs/new/actions.ts"), /uploadInputFile/);
  assert.match(read("src/app/workflow-runs/new/actions.ts"), /detectWorkflowType/);
  assert.match(read("src/app/workflow-runs/new/form.tsx"), /useActionState/);
  assert.match(read("src/app/workflow-runs/new/form.tsx"), /Auto-detect workflow type/);
  assert.match(read("src/app/workflow-runs/new/form.tsx"), /\.csv/);
  assert.match(read("src/app/workflow-runs/new/form.tsx"), /CSV Preview/);
  assert.match(read("src/app/workflow-runs/[id]/page.tsx"), /Input Missing/);
});

test("workflow API client exposes workflow and uploaded input calls", () => {
  const api = read("src/lib/api.ts");
  const apiUrl = read("src/lib/api-url.ts");

  assert.match(api, /apiUrl/);
  assert.match(apiUrl, /resolveApiBaseUrl/);
  assert.match(apiUrl, /isDockerServiceUrl/);
  assert.match(apiUrl, /hostname === "api"/);
  assert.match(apiUrl, /!isContainer/);

  assert.match(api, /export async function listWorkflowRuns/);
  assert.match(api, /export async function getWorkflowRun/);
  assert.match(api, /export async function createWorkflowRun/);
  assert.match(api, /export async function createUploadedInput/);
  assert.match(api, /export async function uploadInputFile/);
  assert.match(api, /export async function getUploadedInput/);
  assert.match(api, /export async function detectWorkflowType/);
  assert.match(api, /export async function listAgentSteps/);
  assert.match(api, /export async function listWorkflowEvents/);
  assert.match(api, /export async function getEvaluationSummary/);
  assert.match(api, /export async function listEvaluationResults/);
  assert.match(api, /export async function getEvaluationComparisons/);
  assert.match(api, /export async function getAgentPerformanceSummary/);
  assert.match(api, /export async function listPromptVersions/);
  assert.match(api, /export async function getPromptVersion/);
  assert.match(api, /export async function createPromptVersion/);
  assert.match(api, /export async function activatePromptVersion/);
  assert.match(api, /export async function listAgentSettings/);
  assert.match(api, /export async function updateAgentSetting/);
  assert.match(api, /export async function runSalesAnalyst/);
  assert.match(api, /export async function runSalesBaseline/);
  assert.match(api, /export async function runSalesReviewer/);
  assert.match(api, /export async function runSalesWriter/);
  assert.match(api, /export async function cancelWorkflowRun/);
  assert.match(api, /export async function listHumanApprovals/);
  assert.match(api, /export async function getHumanApproval/);
  assert.match(api, /export async function getHumanFeedbackSummary/);
  assert.match(api, /export async function approveHumanApproval/);
  assert.match(api, /export async function requestHumanApprovalRetry/);
  assert.match(api, /export async function rejectHumanApproval/);
  assert.match(api, /export async function editHumanApproval/);
});
